"""empty message

Revision ID: 2b4fbf836697
Revises: ea162a0c3ce1
Create Date: 2020-05-07 15:32:20.759322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4fbf836697'
down_revision = 'ea162a0c3ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean()))
    op.execute('UPDATE artist SET seeking_venue = FALSE WHERE seeking_venue IS NULL')
    op.alter_column('artist', 'seeking_venue', nullable=False, server_default="0")

    op.add_column('artist', sa.Column('seeking_description', sa.String(length=120)))

    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean()))
    op.execute('UPDATE venue SET seeking_talent = FALSE WHERE seeking_talent IS NULL')
    op.alter_column('venue', 'seeking_talent', nullable=False, server_default="0")

    op.add_column('venue', sa.Column('seeking_description', sa.String(length=120)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'seeking_artists')
    op.drop_column('artist', 'seeking_venues')
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
